### ISSUE TITLE
Disabling entire layout doesn't work

### ISSUE THREAD

**Issue by henhal** [eclipsesource/jsonforms#1499]
**Describe the bug**

If applying a rule to an entire layout, with ENABLE or DISABLE effect, nothing happens when triggering the rule. SHOW/HIDE works fine, but ENABLE/DISABLE shows no visible difference, and the controls within the layout are still selectable etc.

**To Reproduce**

Create a schema such as

```
type: object
properties:
  foo:
    type: boolean
  bar:
    type: string
  baz:
    type: string
```

And a UI schema such as

```
type: VerticalLayout
elements:
  - type: Control
    scope: "#/properties/foo"
  - type: VerticalLayout
    rule:
      effect: ENABLE
      condition:
        scope: "#/properties/foo"
        schema: 
          const: true
    elements:
      - type: Control
        scope: "#/properties/bar"
      - type: Control
        scope: "#/properties/baz"
```

**Expected behavior**

When `foo` is `false`, the vertical layout containing `bar` and `baz` should be disabled, reasonably meaning that each child in it should recursively be disabled.

**Screenshots**

**Browser (please complete the following information):**
 - Browser Chrome
 - Version 76.0.3809.132

**Used Setup (please complete the following information):**

Default seed test app with only schema and UI schema altered.

**Additional context**
