### ISSUE TITLE
Disabling a control with format time has no effect

### ISSUE THREAD

**Issue by henhal** [eclipsesource/jsonforms#1500]
**Describe the bug**

A rule with effect DISABLE used on a time control has no effect. It's still possible to enter a time and use the up/down arrows etc.
Using DISABLE on date controls however work fine.

**To Reproduce**

Create a schema such as

```
type: object
properties:
  foo:
    type: boolean
  bar:
    type: string
    format: time
```

and a UI schema such as

```
type: VerticalLayout
elements:
  - type: Control
    scope: "#/properties/foo"
  - type: Control
    scope: "#/properties/bar"
    rule:
      effect: ENABLE
      condition:
        scope: "#/properties/foo"
        schema: 
          const: true
```

**Expected behavior**

When the time control `bar` is disabled by triggering the rule (foo: false), it should not be possible to edit the value in the time control.

**Screenshots**

**Browser (please complete the following information):**
 - Browser: Chrome
 - Version: 76.0.3809.132

**Used Setup (please complete the following information):**

Standard seed test app with only schema/ui schema replaced.

**Additional context**
