### ISSUE TITLE
Required enum property offers an empty value

### ISSUE THREAD

**Issue by henhal** [eclipsesource/jsonforms#1501]
**Describe the bug**

If having a enum property with values [foo, bar], the rendered drop-down control will offer values foo, bar or an empty string. 
I can understand that if a property is optional, using an empty value to signal "not a value" may be fine, but when marking the property as required it's still possible to choose an empty value, making for a very strange user experience.

**To Reproduce**

Schema:
```
type: object
required: [mode]
properties:
  mode:
    type: string
    enum: [foo, bar]
```

UI schema:

```
type: VerticalLayout
elements:
  - type: Control
    scope: "#/properties/mode"
```

**Expected behavior**

The enum should offer only foo and bar values, no empty value should be possible to pick since this will violate the schema.

**Screenshots**

**Browser (please complete the following information):**
 - Browser: Chrome
 - Version: 76.0.3809.132

**Used Setup (please complete the following information):**

Standard seed test app

**Additional context**

**Comment by sdirix** [comment]
Thanks for this feature request. Handling enums requires some care. There are multiple things to think about.

When forcing the user to choose one of the enums we need to think about the case where it is not yet set. I would prefer to not choose one by default for the user, as this would modify the data object simply by rendering the form. Therefore we would need to support the empty initial state with a forced selection afterwards.

In general validation errors have different meanings/consequences per application. There are use cases where validation errors might be ignored, for example when saving a WIP state of a form to continue working on it later. In this case I want to be able to unset an enum I'm not yet sure about.

Ideally we would support both use cases (forced and non-forced selection) via an option. Until this option is available we should keep the current behavior as it is the more flexible one.

**Comment by henhal** [comment]
Thanks! Those are some valid concerns, and I agree. If there's no default value set, how to handle that opens up questions. However, I'd claim that a very important and common case is the combination "enum + is required + has default", such as

```
type: object
required: [mode]
properties:
  mode:
    type: string
    enum: [foo, bar]
    default: bar

```
If the schema fulfills these constraints, removing the empty option from the control would be very useful I think.
