### ISSUE TITLE
Vanilla Renderer Radio/Checkbox: add Option for vertical/horizontal layout

### ISSUE THREAD

**Issue by rsoika** [eclipsesource/jsonforms#2103]
### Is your feature request related to a problem? Please describe.

Currently the Readio-Button has always a horizontal layout. This is because of the hard coded css style 'flexDirection=row'.

### Describe the solution you'd like

The Readio-Button Layout can be optimized in an horizontal or vertical design by introducing a new option

     orientation=vertically|horizontally

In this way the layout can be changed by the UISchema:

```yaml
{
  "type": "VerticalLayout",
  "elements": [
    {
      "type": "Group",
      "label": "Simple enum",
      "elements": [
        {
          "type": "Control",
          "scope": "#/properties/exampleRadioEnum",
          "options": {
            "format": "radio",
            "orientation": "vertical"
          }
        }
      ]
    },
    {
      "type": "Group",
      "label": "One of Enum",
      "elements": [
        {
          "type": "Control",
          "scope": "#/properties/exampleRadioOneOfEnum",
          "options": {
            "format": "radio"
          }
        }
      ]
    }
  ]
}
```

The new implementation in the file 'RadioGroup.tsx' can look like this:

```javascript
....
  let groupStyle: { [x: string]: any } = {};
  // compute flexDirection based on the optional option 'orientation=vertical|horizontal'
  if (hasRadioClass) {
    groupStyle = {
      display: 'flex',
      flexDirection: ('vertical' === uischema.options.orientation) ? 'row' : 'column'
    };
  }
....
```

Result:

![image](https://user-images.githubusercontent.com/1339124/221670127-31f18f95-1479-4d02-a381-858418dea1ff.png)

### Describe alternatives you've considered

An alternative would be to allow overwriting or providing optional layout classes. 

### Framework

React

### RendererSet

Vanilla

### Additional context

See discussion here: https://jsonforms.discourse.group/t/is-it-possible-to-arange-radio-checkbox-options-vertical/1352/6
